In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('Cars_24.csv')

In [3]:
df.head()

selling_price    year  km_driven  mileage  engine  max_power   age  \
0           1.20  2012.0     120000    19.70   796.0      46.30  11.0   
1           5.50  2016.0      20000    18.90  1197.0      82.00   7.0   
2           2.15  2010.0      60000    17.00  1197.0      80.00  13.0   
3           2.26  2012.0      37000    20.92   998.0      67.10  11.0   
4           5.70  2015.0      30000    22.77  1498.0      98.59   8.0   

      make                                      model  Individual  \
0   MARUTI                                   ALTO STD           1   
1  HYUNDAI                             GRAND I10 ASTA           1   
2  HYUNDAI                                   I20 ASTA           1   
3   MARUTI                     ALTO K10 2010-2014 VXI           1   
4     FORD  ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV           0   

   Trustmark Dealer  Diesel  Electric  LPG  Petrol  Manual  5  >5  
0                 0       0         0    0       1       1  1   0  
1                 0       0         0    0       1       1  1   0  
2                 0       0         0    0       1       1  1   0  
3                 0       0         0    0       1       1  1   0  
4                 0       1         0    0       0       1  1   0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19820 entries, 0 to 19819
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   selling_price     19820 non-null  float64
 1   year              19820 non-null  float64
 2   km_driven         19820 non-null  int64  
 3   mileage           19820 non-null  float64
 4   engine            19820 non-null  float64
 5   max_power         19820 non-null  float64
 6   age               19820 non-null  float64
 7   make              19820 non-null  object 
 8   model             19820 non-null  object 
 9   Individual        19820 non-null  int64  
 10  Trustmark Dealer  19820 non-null  int64  
 11  Diesel            19820 non-null  int64  
 12  Electric          19820 non-null  int64  
 13  LPG               19820 non-null  int64  
 14  Petrol            19820 non-null  int64  
 15  Manual            19820 non-null  int64  
 16  5                 19820 non-null  int64 

In [5]:
df.isnull().sum()

selling_price       0
year                0
km_driven           0
mileage             0
engine              0
max_power           0
age                 0
make                0
model               0
Individual          0
Trustmark Dealer    0
Diesel              0
Electric            0
LPG                 0
Petrol              0
Manual              0
5                   0
>5                  0
dtype: int64

In [6]:
df.shape

(19820, 18)

In [7]:
df['make'].head()

0     MARUTI
1    HYUNDAI
2    HYUNDAI
3     MARUTI
4       FORD
Name: make, dtype: object

In [8]:
df['model'].head()

0                                     ALTO STD
1                               GRAND I10 ASTA
2                                     I20 ASTA
3                       ALTO K10 2010-2014 VXI
4    ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV
Name: model, dtype: object

In [9]:
df['model'].nunique()

3233

In [10]:
df['make'].nunique()

41

In [11]:
from category_encoders import TargetEncoder

In [12]:
encoder1 = TargetEncoder(cols =['make'])
df['make'] = encoder1.fit_transform(df['make'], df['selling_price'])

In [13]:
encoder2 = TargetEncoder(cols =['model'])
df['model'] = encoder2.fit_transform(df['model'], df['selling_price'])

In [14]:
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [15]:
X.head()

year  km_driven  mileage  engine  max_power   age      make     model  \
0  2012.0     120000    19.70   796.0      46.30  11.0  4.684721  5.235537   
1  2016.0      20000    18.90  1197.0      82.00   7.0  5.458819  5.527772   
2  2010.0      60000    17.00  1197.0      80.00  13.0  5.458819  5.380584   
3  2012.0      37000    20.92   998.0      67.10  11.0  4.684721  2.268993   
4  2015.0      30000    22.77  1498.0      98.59   8.0  5.858258  6.736442   

   Individual  Trustmark Dealer  Diesel  Electric  LPG  Petrol  Manual  5  >5  
0           1                 0       0         0    0       1       1  1   0  
1           1                 0       0         0    0       1       1  1   0  
2           1                 0       0         0    0       1       1  1   0  
3           1                 0       0         0    0       1       1  1   0  
4           0                 0       1         0    0       0       1  1   0

In [16]:
y.head()

0    1.20
1    5.50
2    2.15
3    2.26
4    5.70
Name: selling_price, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42  )

In [19]:
X_train.shape, y_train.shape

((14865, 17), (14865,))

In [20]:
X_test.shape, y_test.shape

((4955, 17), (4955,))

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
scaled_train = scaler.fit_transform(X_train)
scaled_train

array([[-1.11516895, -0.81076741,  2.0710607 , ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 1.07946178, -0.96876242,  1.41987737, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.7659431 , -0.19826591, -0.975547  , ...,  0.49894865,
        -2.2521776 ,  2.35858303],
       ...,
       [-0.17461292,  0.99333244, -0.04528511, ...,  0.49894865,
         0.44401472, -0.42398338],
       [ 0.45242443,  0.28014297, -0.39413331, ...,  0.49894865,
         0.44401472, -0.42398338],
       [-0.17461292,  0.72404123, -1.73138478, ...,  0.49894865,
        -2.2521776 ,  2.35858303]])

In [23]:
scaled_test = scaler.fit_transform(X_test)
scaled_test

array([[ 0.75374841,  0.30472428,  0.49185575, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.1321067 ,  0.03792084,  0.14228654, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.44292756,  0.18069673,  1.8108969 , ...,  0.48640104,
         0.4459675 , -0.42696065],
       ...,
       [ 0.75374841, -0.27214802,  1.03019233, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.44292756, -0.34425706, -0.96235216, ...,  0.48640104,
        -2.24231589,  2.34213622],
       [-0.17871415, -0.02657348,  0.39164591, ...,  0.48640104,
         0.4459675 , -0.42696065]])

In [24]:
X_train[X_train.columns] = scaled_train

In [25]:
X_train.head()

year  km_driven   mileage    engine  max_power       age      make  \
18869 -1.115169  -0.810767  2.071061 -0.441997  -0.545491  1.115169 -0.526860   
3198   1.079462  -0.968762  1.419877  0.043501  -0.009973 -1.079462 -0.159551   
14770  0.765943  -0.198266 -0.975547  2.874926  -0.325906 -0.765943 -0.612940   
16545  0.452424  -0.517348  0.073323 -0.756600  -0.678810 -0.452424 -0.307328   
7508  -2.369244   2.191138 -2.184887  1.705847   1.202222  2.369244 -0.159551   

          model  Individual  Trustmark Dealer    Diesel  Electric       LPG  \
18869 -0.880032   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
3198   0.349767    1.250880         -0.100623  1.013069 -0.020095 -0.053862   
14770 -0.133186   -0.799437         -0.100623  1.013069 -0.020095 -0.053862   
16545 -1.126174    1.250880         -0.100623 -0.987100 -0.020095 -0.053862   
7508   0.227251   -0.799437         -0.100623 -0.987100 -0.020095 -0.053862   

         Petrol    Manual         5        >5  
18869 -0.972330  0.498949  0.444015 -0.423983  
3198  -0.972330  0.498949  0.444015 -0.423983  
14770 -0.972330  0.498949 -2.252178  2.358583  
16545  1.028457  0.498949  0.444015 -0.423983  
7508   1.028457 -2.004214  0.444015 -0.423983

In [26]:
X_test[X_test.columns] = scaled_test

In [27]:
scaled_test

array([[ 0.75374841,  0.30472428,  0.49185575, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.1321067 ,  0.03792084,  0.14228654, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.44292756,  0.18069673,  1.8108969 , ...,  0.48640104,
         0.4459675 , -0.42696065],
       ...,
       [ 0.75374841, -0.27214802,  1.03019233, ...,  0.48640104,
         0.4459675 , -0.42696065],
       [ 0.44292756, -0.34425706, -0.96235216, ...,  0.48640104,
        -2.24231589,  2.34213622],
       [-0.17871415, -0.02657348,  0.39164591, ...,  0.48640104,
         0.4459675 , -0.42696065]])

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
model = LinearRegression()

In [30]:
model.fit(X_train,y_train)

LinearRegression()

In [31]:
pred_train = model.predict(X_train)
pred_train

array([2.43069487, 8.21501748, 7.25335759, ..., 4.23677639, 7.59682523,
       7.91456044])

In [32]:
model.coef_

array([ 0.7086768 , -0.23304777, -0.20822646,  0.11395199,  1.24120716,
       -0.7086768 ,  1.50379923,  1.18319752, -0.11028765, -0.03662805,
        0.19601818,  0.07803259, -0.00200932, -0.20187893, -0.43030697,
       -0.09287471,  0.00347571])

In [33]:
model.intercept_

np.float64(6.586707923309764)

In [34]:
pred_test = model.predict(X_test)
pred_test

array([6.25074461, 5.77281847, 6.90247124, ..., 3.17689799, 9.80923556,
       4.36848661])

In [35]:
from sklearn.metrics import mean_squared_error

In [36]:
train_mse = mean_squared_error(y_train, pred_train, squared = False )
train_mse

C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


np.float64(1.8360675074925843)

In [37]:
test_mse = mean_squared_error(y_test, pred_test, squared = False )
test_mse

C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


np.float64(1.8274710434445482)

--> R2 SCORE :-

In [38]:
round(model.score(X_train, y_train),2)*100

86.0

In [39]:
round(model.score(X_test, y_test),2)*100

86.0